/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

import java.awt.Font;
import java.io.IOException;
import java.io.*;
import javax.swing.JFileChooser;
import java.nio.*;
import java.nio.file.Files;
import java.util.stream.Stream;
import javax.print.DocFlavor;

/**
 *
 * @author RunzeTang
 */
public class Editor extends javax.swing.JFrame 
{
    File currentFile;
    public Editor() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        toolBar = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        statusBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileOpen = new javax.swing.JMenuItem();
        menuFileSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("文本编辑器");
        setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(1);
        textArea.setTabSize(1);
        textArea.setDoubleBuffered(true);
        textArea.setMargin(new java.awt.Insets(0, 2, 0, 2));
        jScrollPane2.setViewportView(textArea);

        toolBar.setBackground(new java.awt.Color(255, 255, 255));
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setDoubleBuffered(true);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("工具栏");
        toolBar.add(jLabel2);

        statusBar.setBackground(new java.awt.Color(204, 255, 255));
        statusBar.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText("状态栏");
        statusBar.add(jLabel1, java.awt.BorderLayout.LINE_START);

        menuBar.setFont(menuBar.getFont().deriveFont(menuBar.getFont().getSize()+3f));

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        menuFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuFileOpen.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        menuFileOpen.setText("打开");
        menuFileOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuFileOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuFileOpen);

        menuFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuFileSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        menuFileSave.setText("保存");
        menuFileSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menuFileSaveActionPerformed(evt);
            }
        });
        menuFile.add(menuFileSave);

        menuBar.add(menuFile);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuFileOpenActionPerformed
    {//GEN-HEADEREND:event_menuFileOpenActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        int i=fileChooser.showOpenDialog(null);
        if(i!= JFileChooser.APPROVE_OPTION) return;  //如果用户没有选择文件
        currentFile=fileChooser.getSelectedFile();
        try (BufferedReader reader=Files.newBufferedReader(currentFile.toPath()))
         {
                    int ch;
                    StringBuffer str=new StringBuffer();
                    while ((ch=reader.read())!=-1)
                     {
                         str.append((char)ch);
                     }
                    textArea.append(str.toString());
                    reader.close();
         }
         catch (IOException x)
         {
                    System.err.format("IOException: %s%n", x);
          }
    }//GEN-LAST:event_menuFileOpenActionPerformed

    private void menuFileSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuFileSaveActionPerformed
    {//GEN-HEADEREND:event_menuFileSaveActionPerformed
        try (BufferedWriter writer=Files.newBufferedWriter(currentFile.toPath()))
        {
            writer.write(textArea.getText());
            writer.close();
        }
        catch (IOException x)
        {
            System.err.format("IOException: %s%n", x);
        }
    }//GEN-LAST:event_menuFileSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileOpen;
    private javax.swing.JMenuItem menuFileSave;
    private javax.swing.JPanel statusBar;
    private javax.swing.JTextArea textArea;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    public static class Config
    {
        public static Font textareaFont;
    }
}
